# Model
model_name: "meta-llama/Llama-3.2-3B-Instruct"  # Replace with your base model must be compatible with the tokenizer and transformers library
tokenizer_name: "meta-llama/Llama-3.2-3B-Instruct"

# Training Args
epochs: 1
batch_size: 4
number_processes: 8
# pad_token: 128263
save_steps: 1000
learning_rate: 5.0e-5

# Datasets
# text_QA_dataset: "amuvarma/text-messages-6m-processed-1-2g-8192l"
# TTS_dataset: "amuvarma/snac-10m-tts-combined"
training_dataset: "UjjD/tts_dataset_1.05M_padded_text_labels_on" #"UjjD/tts_dataset_1.05M_padded_text_labels_on"

# Naming and paths
save_folder: "checkpoints"
project_name: "tts-fresh-comparisons-3"
run_name: "no bf16"