_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 71
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.6
            "6": 4.48.3
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
batch_size:
    value: 1
dataset:
    value: UjjD/tts_dataset_1.05M_padded
epochs:
    value: 1
learning_rate:
    value: 0.0009
model_name:
    value: meta-llama/Llama-3.2-3B-Instruct
